num1 = input('Enter a Number :')
num2 = input('Enter a Number :')
Add = float(num1) +  float(num2)
Sub = float(num1) -  float(num2)
Mul = float(num1) *  float(num2)
Div = float(num1) /   float(num2)
print(Add)
print(Sub)
print(Mul)
print(Div)

